#Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#Importing the dataset

In [2]:
data = pd.read_csv("/content/50 startup project.txt")
data.head()

R&D Spend  Administration  Marketing Spend     Profit
0  165349.20       136897.80        471784.10  192261.83
1  162597.70       151377.59        443898.53  191792.06
2  153441.51       101145.55        407934.54  191050.39
3  144372.41       118671.85        383199.62  182901.99
4  142107.34        91391.77        366168.42  166187.94

#Checking for Missing value

In [3]:

data.isnull().sum()

R&D Spend          0
Administration     0
Marketing Spend    0
Profit             0
dtype: int64

#MULTIPLE LINEAR REGRESSION



#Initiating the *variables*

In [4]:
X = data.drop(['Profit'], axis = 1)
y = data['Profit'].values.reshape(-1,1)

#Splitting data into training, testing datase

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Fitting Linear regression to our training set

In [6]:
from sklearn.linear_model import LinearRegression
multiple_reg = LinearRegression()
multiple_reg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

#Testing

In [7]:
y_pred = multiple_reg.predict(X_test)

#Calculating the coefficients

In [8]:
multiple_reg.coef_

array([[ 0.80377928, -0.06792917,  0.03124155]])

#Calculating the intercept

In [9]:
multiple_reg.intercept_

array([54071.87574599])

#Calculating the R squared value

In [10]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9000653083037321

In [11]:
output = multiple_reg.predict([[165349.20,136897.80,471784.10]])
output

array([[192416.0460853]])